[build]
  publish = "build/web"
  command = "bash ./install_flutter.sh && export PATH=\"$PATH:`pwd`/flutter/bin\" && flutter build web --release"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
