name: Build Flutter (Web & APK)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Verify Flutter installation
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze || true

      - name: Build Web version
        run: flutter build web --release

      - name: Zip Web build
        run: |
          cd build/web
          zip -r ../../web-build.zip .
          cd ../..
        continue-on-error: true

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web-build.zip

      - name: Build APK
        run: flutter build apk --release
        continue-on-error: true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
