name: Build Flutter Web & Android
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Linux deps
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev liblzma-dev zip unzip

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze || true

      - name: Build Web
        env: { CI: false }
        run: |
          flutter config --enable-web
          flutter build web --release --target=lib/main.dart

      - name: Zip Web
        run: cd build/web && zip -r ../../web_build.zip . && cd ../..

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web_build
          path: web_build.zip

      - name: Build APK
        env: { CI: false }
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_release
          path: build/app/outputs/flutter-apk/app-release.apk
