name: Build Flutter Web & Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: stable

      - name: Enable Linux dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev liblzma-dev zip unzip

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Get Flutter packages
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze || true

      - name: Build Flutter Web
        run: flutter build web --release --target=lib/main.dart

      - name: Archive Web build
        run: |
          cd build/web
          zip -r ../../web_build.zip .
          cd ../..
        continue-on-error: true

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web_build
          path: web_build.zip

      - name: Build Flutter APK
        run: flutter build apk --release
        continue-on-error: true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_release
          path: build/app/outputs/flutter-apk/app-release.apk
