name: Build & Deploy Flutter Web

on:
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install system deps
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev liblzma-dev zip unzip

      - name: Pub get
        run: flutter pub get

      - name: Build Web
        env:
          CI: false
        run: |
          flutter config --enable-web
          flutter build web --release --target=lib/main.dart

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web_build
          path: build/web

      # ⬇️ Автодеплой на Netlify (APK не собираем)
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: ./build/web
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
